version: '3'

services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    environment:
      - SYNAPSE_SERVER_NAME=chatgenius.local
      - SYNAPSE_REPORT_STATS=no
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=synapse_password
      - POSTGRES_DB=synapse
    volumes:
      - ./synapse/data:/data
    ports:
      - "8008:8008"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - matrix-network

  postgres:
    image: postgres:15-alpine
    container_name: synapse-postgres
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=synapse_password
      - POSTGRES_DB=synapse
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - matrix-network

  redis:
    image: redis:7-alpine
    container_name: chatgenius-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis_password}
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    restart: unless-stopped
    networks:
      - matrix-network

networks:
  matrix-network:
    driver: bridge
