server_name: 'localhost'
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false

# User directory configuration
user_directory:
  enabled: true
  search_all_users: true
  prefer_local_users: true
  show_all_users: true
  search_list_all_users: true
  allow_public_rooms_without_auth: true
  allow_list_all_users: true
  search_results_limit_per_query: 100
  refresh_interval_seconds: 300
  update_user_directory: true

# Enable user search
enable_search: true
search_prefer_local_users: true
search_all_users: true

database:
  name: psycopg2
  args:
    database: synapse
    user: synapse
    password: changeme
    host: postgres
    cp_min: 5
    cp_max: 10

log_config: '/data/localhost.log.config'

# Media store configuration
media_store_path: /data/media_store
dynamic_thumbnails: true
thumbnail_sizes:
  - width: 32
    height: 32
    method: crop
  - width: 96
    height: 96
    method: crop
  - width: 320
    height: 240
    method: scale
  - width: 400
    height: 400
    method: crop
  - width: 640
    height: 480
    method: scale
  - width: 800
    height: 600
    method: scale

# Thumbnail generation settings
thumbnail_requirements:
  width: 4096
  height: 4096
  method: scale
  media_type: image/jpeg,image/jpg,image/png,image/webp,image/gif
  min_download_bytes: 0
  max_download_bytes: 50000000

# Media repository settings
max_pending_uploads: 100
max_upload_size: '50M'
max_image_pixels: '32M'
media_storage_providers: []

# URL preview configuration
url_preview_enabled: true
url_preview_ip_range_blacklist:
  - '127.0.0.0/8' # Loopback
  - '10.0.0.0/8' # RFC1918 networks
  - '172.16.0.0/12' # RFC1918 networks
  - '192.168.0.0/16' # RFC1918 networks
  - '169.254.0.0/16' # Link-local
  - '::1/128' # Loopback IPv6
  - 'fe80::/64' # Link-local IPv6
  - 'fc00::/7' # Private IPv6
url_preview_ip_range_whitelist: []
max_spider_size: '10M'

media_retention:
  local_media_lifetime: 30d
  remote_media_lifetime: 30d

# Registration settings
enable_registration: true
enable_registration_without_verification: true
registration_requires_token: false
verify_registration_requests_by_email: false
allow_guest_access: false
report_stats: false
disable_registration_emails: true
enable_3pid_lookup: false

# Security settings
macaroon_secret_key: 'generate_a_secure_random_key_here'
form_secret: 'generate_another_secure_random_key_here'
registration_shared_secret: 'generate_yet_another_secure_random_key_here'

# Federation settings
federation_domain_whitelist:
  - 'matrix.org'
suppress_key_server_warning: true

# Rate limiting configuration
rc_message:
  per_second: 0.2
  burst_count: 10
rc_registration:
  per_second: 0.17
  burst_count: 3
rc_login:
  address:
    per_second: 0.17
    burst_count: 3
  account:
    per_second: 0.17
    burst_count: 3
  failed_attempts:
    per_second: 0.17
    burst_count: 3

# Media upload rate limits
rc_uploads_per_user:
  per_second: 0.1
  burst_count: 10
rc_invites:
  per_room:
    per_second: 0.3
    burst_count: 3
  per_user:
    per_second: 0.2
    burst_count: 3

trusted_key_servers:
  - server_name: 'matrix.org'

# Presence configuration
presence:
  enabled: true
  presence_stream_timeout_seconds: 60
  presence_invite_timeout: 60
  presence_updates_per_room: 100
  presence_updates_per_user: 100
