server_name: 'localhost'
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false

database:
  name: psycopg2
  args:
    database: synapse
    user: synapse
    password: changeme
    host: postgres
    cp_min: 5
    cp_max: 10

log_config: '/data/localhost.log.config'
media_store_path: /data/media_store

# Registration settings
enable_registration: true
enable_registration_without_verification: true
registration_requires_token: false
verify_registration_requests_by_email: false
allow_guest_access: false
report_stats: false
disable_registration_emails: true
enable_3pid_lookup: false

# Security settings
macaroon_secret_key: 'generate_a_secure_random_key_here'
form_secret: 'generate_another_secure_random_key_here'
registration_shared_secret: 'generate_yet_another_secure_random_key_here'

# Federation settings
federation_domain_whitelist:
  - 'matrix.org'
suppress_key_server_warning: true

# Rate limiting configuration
rc_message:
  per_second: 0.2
  burst_count: 10
rc_registration:
  per_second: 0.17
  burst_count: 3
rc_login:
  address:
    per_second: 0.17
    burst_count: 3
  account:
    per_second: 0.17
    burst_count: 3
  failed_attempts:
    per_second: 0.17
    burst_count: 3

trusted_key_servers:
  - server_name: 'matrix.org'
